name: publish_nuget
on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  publish_nuget:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
    
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
    
        - run: dotnet nuget add source --username GH_ACTIONS --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LightBlueFox-Labs/index.json"

        - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
    
        - name: Publish NuGet package
          run: |
            foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
                dotnet nuget push $file --source "github" --skip-duplicate
            }
